mongodb:
  # docker-composeで定義したサービス名「mongo」をホスト名として使用
  dsn: "mongodb://mongo:27017/notification_service"
  database: "notification_service"
  user_collection: "user_notifications"
  status_collection: "user_read_status"

nats:
  # NATSサーバーが別コンテナで存在する場合は、同じように「nats」に変更（未構築ならコメントでもOK）
  address: "nats://nats:4222"

keycloak:
  # Keycloakもdocker-composeで立てるならlocalhostではなく「keycloak」などに変える必要あり
  keycloak_base_url: "http://keycloak:8080/realms/internet-service-relm"
  client_id: "insurance-app"
