postgres:
  dsn: "postgresql+asyncpg://appuser:password@localhost:5432/insurance_db"
  echo: False

mongodb:
  dsn: "mongodb://localhost:27017/quote_db"
  database: "quote_db"
  collection: "interest_rates"
  scenario_collection: "quote_scenarios"

nats:
  address: "nats://localhost:4222"

keycloak:
  keycloak_base_url: "http://localhost:8080/realms/internet-service-relm"
  client_id: "insurance-app"

session:
  normal_ttl: 1800
  rememberme_ttl: 2592000

pension:
  min_age: 20
  max_age: 70
  min_payment_years: 15
  max_annual_tax_deduction: 40000
  plan_code: "PENSION_001"