postgres:
  dsn: "postgresql://appuser:password@localhost:5432/insurance_db"
  echo: True

mongodb:
  dsn: "mongodb://localhost:27017/rate_db"
  database: "rate_db"
  collection: "interest_rates"

nats:
  address: "nats://localhost:4222"

keycloak:
  keycloak_base_url: "http://localhost:8080/realms/internet-service-relm"
  client_id: "insurance-app"

session:
  normal_ttl: 1800
  rememberme_ttl: 2592000

pension:
  min_age: 20
  max_age: 70
  min_payment_years: 15
  max_annual_tax_deduction: 40000