mongodb:
  dsn: "mongodb://mongodb:27017/notification_service"
  database: "notification_service"
  global_collection: "global_notifications"

nats:
  address: "nats://nats:4222"

keycloak:
  keycloak_base_url: "http://localhost:8080/realms/internet-service-relm"
  client_id: "insurance-app"