postgres:
  dsn: "postgresql+asyncpg://appuser:password@localhost:5432/insurance_db"
  echo: False

mongodb_rate:
  dsn: "mongodb://localhost:27017/quote_db"
  database: "quote_db"
  collection: "interest_rates"

mongodb:
  dsn: "mongodb://localhost:27017/quote_db"
  database: "application_db"
  collection: "application_beneficiaries"
  scenario_collection: "application_scenarios"

nats:
  address: "nats://localhost:4222"

keycloak:
  keycloak_base_url: "http://localhost:8080/realms/internet-service-relm"
  client_id: "insurance-app"

session:
  normal_ttl: 1800
  rememberme_ttl: 2592000

services:
  quotation_service_url: "http://localhost:8000"

pension:
  min_age: 20
  max_age: 70
  min_payment_years: 15
  max_annual_tax_deduction: 40000
  plan_code: "PENSION_001"